### ISSUE TITLE
TOC 目录列表限制字符个数的问题

### ISSUE THREAD

**Issue by baagod** [kevinzhao2233/typora-theme-pie#1]
主题很棒，很喜欢！
但是有个问题，插入目录列表的时候，列表中有字符数显示不完整。请问这块可以优化一下吗？
![image](https://user-images.githubusercontent.com/39392770/79541229-05ef5780-80bc-11ea-99dd-ee21d10e7aad.png)

**Comment by baagod** [comment]
经测试发现这样，如果标题是：# 任意字符串+2个空格以上。
就会出现上面那种情况。

**Comment by kevinzhao2233** [comment]
> 经测试发现这样，如果标题是：# 任意字符串+2个空格以上。
> 就会出现上面那种情况。

谢谢反馈，已经有解决方案了：在目录中取消多余的空格（只显示一个空格），但这可能会限制你的书写习惯

**Comment by baagod** [comment]
@kevinzhao2233 只有一个空格确实可以啊。但是用过的主题中都没有出现过这种情况，希望能兼容下就最好，感谢！

**Comment by kevinzhao2233** [comment]
已经解决，帮忙下载试试看，只下载 pie.css 即可

**Comment by baagod** [comment]
![image](https://user-images.githubusercontent.com/39392770/79547039-f07f2b00-80c5-11ea-92b5-807761ad0110.png)
好了，很完美，非常感谢！
