### ISSUE TITLE
mermaid回车时跳转

### ISSUE THREAD

**Issue by zhiweicao** [kevinzhao2233/typora-theme-pie#10]
mermaid流程图时，视图会异常跳转，其他主题没有这个问题
![ezgif-3-1a27ef6f11ff](https://user-images.githubusercontent.com/26926126/102360128-9932b100-3fec-11eb-9bf9-3ea0710395c9.gif)

**Comment by kevinzhao2233** [comment]
我自己测试并没有出现这个问题，不知道你更新到最新版是否还有
