### ISSUE TITLE
❤

### ISSUE THREAD

**Issue by LuoZIren** [kevinzhao2233/typora-theme-pie#11]
请问安装更纱黑体具体是哪一款？通过您提供的链接下载了一个ttf的字体包，里面的内容太多了，总不会是全部安装……

**Comment by kevinzhao2233** [comment]
谢谢，建议安装 sarasa-mono-sc 系列的，即下图所示的部分：
![image](https://user-images.githubusercontent.com/42138464/103497589-fba8ff80-4e7c-11eb-9f90-4b62278df299.png)
当然全部安装也可，并无影响。
