### ISSUE TITLE
代码块+超链接显示优化问题。

### ISSUE THREAD

**Issue by kebinzhi** [kevinzhao2233/typora-theme-pie#12]
现在超链接文字是这样显示的：
![for](https://user-images.githubusercontent.com/20044735/107146572-26a6d780-6984-11eb-97ce-9c836b9c7dae.png)
代码块+超链接是这样显示的：
![代码块](https://user-images.githubusercontent.com/20044735/107146586-3a523e00-6984-11eb-9d97-cbf64acbe9fa.png)
二者区别，1是字体色彩，普通超链接字色会深一些。2是下划线，普通超链接能全显示。
能不能把代码块+超链接的字色显示和普通超链接一样，然后下划线全显示出来。
类似这样：
![显示](https://user-images.githubusercontent.com/20044735/107146680-a7fe6a00-6984-11eb-81b9-30108e985738.png)

**Comment by kebinzhi** [comment]
自己解决了

**Comment by kevinzhao2233** [comment]
哈哈哈哈，不好意思，昨天感冒了，谢谢提醒
