### ISSUE TITLE
复制进微信公众号编辑器内，格式会消失，如：标题前的竖杠、引用符号都会消失

### ISSUE THREAD

**Issue by maodandandan** [kevinzhao2233/typora-theme-pie#13]
如题

**Comment by kevinzhao2233** [comment]
感谢您的反馈。
Typora 本身复制时只会复制 Markdown 源码，而主题样式是脱离 Markdown 的。我没有用过微信公众号编辑器，所以也不清楚其逻辑，但按理说您的需求没办法通过我来满足，除非 Typora 具有复制样式的功能。

**Comment by maodandandan** [comment]
> 感谢您的反馈。
> Typora本身复制时只会复制降价源码，而主题样式是脱离减价的。我没有用过微信公众号编辑器，所以也不清楚其逻辑，但按理说您的需求没办法通过我来满足，除非Typora具有复制样式的功能。

您好
那太遗憾了，但是如果Typora无法复制样式的话，这个样式不就变成了只能本地使用了？再精美的样式也一样不大呀。

**Comment by kevinzhao2233** [comment]
是的，所有的 Typora 样式都只能本地使用，实际上任何一个支持 Markdown 的编辑器都只是可以将 Markdown 渲染成 HTML，进而绘制到页面上。唯一可以实现多平台同一套样式的方式就是将一套样式适配到多个平台，但这确实不是普通开发者可以随意做到的。
