### ISSUE TITLE
建议暗黑模式的背景颜色使用如下的样式

### ISSUE THREAD

**Issue by Aurorxa** [kevinzhao2233/typora-theme-pie#16]
#2b2b2b，这个是IDEA默认的样式，您默认的貌似太蓝了

**Comment by kevinzhao2233** [comment]
主题这个东西本就是每个人有每个人的喜好，pie 的背景蓝色也是经过很长时间才确定下来，我认为使用偏蓝色，相比于灰黑色更有力量感。
而这些都是我个人的感受，对于你就又不是那么贴切。
所以我建议你 fork 本主题，然后修改掉 `--side-bar-bg-color` 和 `--bg-color` 两个颜色即可

**Comment by Aurorxa** [comment]
OK

**Comment by lilisore** [comment]
> 主题这个东西本就是每个人有每个人的喜好，pie 的背景蓝色也是经过很长时间才确定下来，我认为使用偏蓝色，相比于灰黑色更有力量感。 而这些都是我个人的感受，对于你就又不是那么贴切。 所以我建议你 fork 本主题，然后修改掉 `--side-bar-bg-color` 和 `--bg-color` 两个颜色即可

请问现版本，已无法找到--bg-color，该用哪个参数修改，谢谢告知
