### ISSUE TITLE
流程图代码显示 bug

### ISSUE THREAD

**Issue by yistc** [kevinzhao2233/typora-theme-pie#19]
Hi ~ 最近发现流程图代码会有如图的显示bug, 代码和 Line number 挨的很近。 重启 Typora 后已有的流程图代码块显示会恢复正常, 但新建的代码块还是会这样
![2021-08-27-14-39-oVVVXsKu@2x](https://user-images.githubusercontent.com/32131698/131083503-982f88db-0342-478d-9597-7bd2be00cfca.png)

**Comment by kevinzhao2233** [comment]
测试并没有复现，可能是当时这个版本恰好有问题吧
