### ISSUE TITLE
列表不对齐的问题

### ISSUE THREAD

**Issue by baagod** [kevinzhao2233/typora-theme-pie#2]
![image](https://user-images.githubusercontent.com/39392770/79836971-5a0f7a00-83e3-11ea-8020-e7430c682014.png)

`-` 是有序的，数字会偏移。

在 github 测试是对齐的：

1. 户端向服务器发送 HTTP 协议请求包，请求服务器里的资源文户端向服务器发送 HTTP 协议请求包，请求服务器里的资源文户

2. 户端向服务器发送 HTTP 协议请求包，请求服务器里的资源文户端向服务器发送 HTTP 协议请求包，请求服务器里的资源文户端向服务器发送

**Comment by kevinzhao2233** [comment]
已经解决，请下载适用。这是以前为了给字体让路留些的坑

**Comment by baagod** [comment]
好滴！谢谢大佬！
