### ISSUE TITLE
关于代码块的设置

### ISSUE THREAD

**Issue by ACodingDay** [kevinzhao2233/typora-theme-pie#20]
在写一些 MySQL 查询语句时，使用该主题会将查询结果排版到第二行，看起来有点难受，如下所示：
[主题 pie](https://gitee.com/yinyingying/blog-pic/raw/master/typora_theme_github.png)
而主题 Github 不会：
[主题 Github](https://gitee.com/yinyingying/blog-pic/raw/master/typora_theme_pie.png)

请问，需要改动什么设置让它像主题 github 一样？

**Comment by kevinzhao2233** [comment]
这个是版心宽度的问题，我个人喜欢比较小的宽度，阅读起来更好，但是你这个问题就会出现，你可以手动修改主题的 CSS 文件里 344 行，将 max-width: 860px; 修改成更大的，或者直接修改成 95% 左右即可
