### ISSUE TITLE
Is there any way to set the paragraph in text-align: justify;

### ISSUE THREAD

**Issue by junweiyang7** [kevinzhao2233/typora-theme-pie#21]
I have tried to add the block code of `p { text-align: justify;}` in multiple places in the CSS file, and nothing really happens after I restart Typora.

**Comment by junweiyang7** [comment]
<img width="461" alt="Screen Shot 2021-12-19 at 2 09 46 PM" src="https://user-images.githubusercontent.com/15006150/146665883-1ef92a2b-f007-49fc-99b8-bcb55b581dec.png">

**Comment by kevinzhao2233** [comment]
Try searching for the `#write p` selector, add `text-align: justify;` here. At about line 349.
