### ISSUE TITLE
typora下渲染html导入公众号显示不全

### ISSUE THREAD

**Issue by advfree** [kevinzhao2233/typora-theme-pie#23]
作者你好，如题，typora下渲染html导入公众号显示不全

比如 一级标题 下面的 横线
二级标题的 红色数显等

**Comment by kevinzhao2233** [comment]
猜测是 typora 和公众号渲染方式不同导致的，建议你去了解一下公众号样式的规则，应该是不能完全匹配 typora 的样式。
