### ISSUE TITLE
您好，请问在css文件中有办法实现typora输入中文符号自动补全的功能吗？

### ISSUE THREAD

**Issue by astar99** [kevinzhao2233/typora-theme-pie#25]
如输入“，自动补全“”的功能；
typora目前只支持英文符号的自动补全功能，不知这个是否是软件本身的问题

**Comment by kevinzhao2233** [comment]
CSS 文件是做不到的，你或许可以去找官方谈谈，不过估计他们也不太愿意实现 😂
