### ISSUE TITLE
请问为什么最新版我的英文字体这么细啊

### ISSUE THREAD

**Issue by Pil0tXia** [kevinzhao2233/typora-theme-pie#26]
![image](https://user-images.githubusercontent.com/41445332/190036457-2e96240d-5744-4d6e-a601-b20ed8848a9e.png)

英文字体太细了，旧版的好像没这样。请问可以修复吗？

**Comment by Pil0tXia** [comment]
![image](https://user-images.githubusercontent.com/41445332/190036724-9a62f4ee-0281-4b06-96a2-b394e8b7b890.png)

大纲这边也是

**Comment by kevinzhao2233** [comment]
感谢反馈，麻烦提供一下你屏幕的分辨率，该问题应该是由于字体不匹配导致的。

**Comment by kevinzhao2233** [comment]
我看了下，上次更新确实丢失了对 更纱黑体 的引用，请重新下载 pie.css 和 pie-dark.css 到你的主题文件夹。另外如果你屏幕分辨率为 1080 左右的，则下载并安装 更纱黑体，如果是 2k 及以上，则请下载 MiSans，显示效果会好很多。

**Comment by Pil0tXia** [comment]
谢谢及时回复。屏幕分辨率是2240x1400。更换css、安装MiSans-Regular字体后英文字体并无改观：
![image](https://user-images.githubusercontent.com/41445332/190066240-c9a35c08-33dd-416a-9e2d-b0e8be424837.png)

**Comment by kevinzhao2233** [comment]
我又把字体处理了一下，你现在可以直接下载 [typora-theme-pie.zip](https://raw.githubusercontent.com/kevinzhao2233/typora-theme-pie/master/typora-theme-pie.zip) 文件，解压到主题文件夹试试。
如果依然不可以的话，麻烦将两个 css 文件里 `--font-normal: ` 对应的那行改为
```css
--font-normal: 'MiSans', '等距更纱黑体 SC', 'Microsoft YaHei', 'Helvetica Neue', Arial, sans-serif;
```
如果依然没有改观，你或许只能使用其他主题了，我确实想不出什么原因导致这样的问题。

**Comment by Pil0tXia** [comment]
这一版的英文好多了！
![image](https://user-images.githubusercontent.com/41445332/190096784-d690a418-b9bf-4b98-9ca6-19267d25bb54.png)
![image](https://user-images.githubusercontent.com/41445332/190096941-c11dcd4b-5129-4c52-94d5-5445683cf000.png)

**Comment by Pil0tXia** [comment]
![image](https://user-images.githubusercontent.com/41445332/190098537-e0bee449-9749-4aee-b8c7-9a6c851226e5.png)
![image](https://user-images.githubusercontent.com/41445332/190098652-ca7abd94-4a34-4536-b2e4-26f6044e17f4.png)
图1是2020年5月份的版本，我用了好几年了，感觉新版的字体变小变轻了，体现在字间距变大了，方块字的占地面积变小了。我试着删除了regular安装了medium，虽然字体变得更重了，但是没有改变字间距和方块字的占地面积。请问有什么建议吗？

**Comment by kevinzhao2233** [comment]
我明白你的意思了，你把 `--font-normal:` 对应行的 `'MiSans',` 删掉即可。或者全文搜索 `'MiSans',` 全部删除也可以。

两年前，MiSans 字体还没有出现，那时的电脑普遍是 1080P 的，基本只有更纱黑体对这个分辨率做了专门的优化，让其渲染的效果比微软雅黑好很多，加之它是开源免费的，我便使用更纱黑体作为默认中文字体。

后来有一次发现小米发布了 MiSans 字体，用过之后个人感觉看起来更舒服（实际就是字间距影响的），我便使用 MiSans 作为默认中文字体。

但不管怎么说，这都是个人喜好的事情，你大可以在我主题的基础上随意修改，做成你喜欢的样子。

**Comment by Pil0tXia** [comment]
感谢。不装Misans和更纱黑体就是微软雅黑了。Misans在幅面更大的显示器上的显示效果也很棒。倒是更纱黑体某些字型（如“质”）与常用的黑体相比有些怪怪的。
