### ISSUE TITLE
请问如何修改高亮的背景色呀？

### ISSUE THREAD

**Issue by astar99** [kevinzhao2233/typora-theme-pie#27]
![image](https://user-images.githubusercontent.com/53571272/197512396-1508ec90-9480-40dd-9a22-461fb51d8811.png)
如图，使用==高亮标注出来的红色背景色有点晃眼。。

**Comment by kevinzhao2233** [comment]
在代码里搜索 heighlight
对应的那个选择器下方修改 background-color 的值即可
比如 background-color: #123456;

**Comment by astar99** [comment]
好的，谢谢！
