### ISSUE TITLE
无序列表与有序列表光标没有居中对齐？

### ISSUE THREAD

**Issue by Cakeyan** [kevinzhao2233/typora-theme-pie#29]
当列表没有打任何字符的时候，无序列表与有序列表后紧跟的光标没有居中。
<img width="46" alt="image" src="https://user-images.githubusercontent.com/77425002/206842736-9cb04bd1-a8a9-4324-93cc-52f4aa2f0f31.png">
<img width="48" alt="image" src="https://user-images.githubusercontent.com/77425002/206842783-b5469bf2-e9f9-4bfc-9afc-f800213484e1.png">

如果在后面跟上一定字符，光标就会居中，这样光标会有一定的位移。
<img width="43" alt="image" src="https://user-images.githubusercontent.com/77425002/206842885-33010770-006a-49f8-98f4-559079d741ed.png">

**Comment by kevinzhao2233** [comment]
抱歉，我没有复现这个问题，请更新 Typora 后看看是否还有这样的问题。

![image](https://user-images.githubusercontent.com/42138464/212580330-dec633d3-0470-4efa-805b-485d5d9d1359.png)
![image](https://user-images.githubusercontent.com/42138464/212580366-9bdc918d-a90b-411e-b490-d5ac606ae78b.png)
