### ISSUE TITLE
暗黑模式

### ISSUE THREAD

**Issue by Nobodylesszb** [kevinzhao2233/typora-theme-pie#3]
你好。我想问一下什么时候开发暗黑模式？

**Comment by kevinzhao2233** [comment]
@Nobodylesszb 刚开始做的时候是以满足个人需求为目的的，我个人是不太喜欢暗黑模式。嗯，，，，后面看情况吧，有时间了做一下

**Comment by Nobodylesszb** [comment]
好的，十分感谢！

**Comment by kevinzhao2233** [comment]
@Nobodylesszb 暗色模式已经上传了，今天刚做的，没做过多的测试，你感兴趣的话可以下载 pie-dark.css 试一试，遇到不好看，不顺眼的帮忙提个 issue 哈

**Comment by Nobodylesszb** [comment]
好的，十分感谢！
---------- Forwarded message ----------
