### ISSUE TITLE
三级标题和四级标题显示错误

### ISSUE THREAD

**Issue by gitccl** [kevinzhao2233/typora-theme-pie#4]
我使用了这个给标题自动编号的css：[给标题自动编号](https://github.com/lipengzhou/typora-theme-auto-numbering/blob/master/base.user.css) , 可是三级标题和四级标题就会是图片里的那样显示不正确，二级标题没问题，怎么解决呢？
![image](https://user-images.githubusercontent.com/60637740/81476127-a4e21c00-9242-11ea-9a75-36e3ed88cb07.png)

**Comment by kevinzhao2233** [comment]
应该是我们俩样式冲突了，我明天看看

**Comment by gitccl** [comment]
> 应该是我们俩样式冲突了，我明天看看

好的，谢谢啦

**Comment by kevinzhao2233** [comment]
@gitccl  问题可以解决，但是比较脆弱，他的那个其实也是个主题。你现在下载 pie.css 试试吧
![Snipaste_2020-05-10_08-56-17](https://user-images.githubusercontent.com/42138464/81488506-21551900-929c-11ea-9171-f302f1baf3a3.png)

**Comment by gitccl** [comment]
> @gitccl 问题可以解决，但是比较脆弱，他的那个其实也是个主题。你现在下载 pie.css 试试吧
> ![Snipaste_2020-05-10_08-56-17](https://user-images.githubusercontent.com/42138464/81488506-21551900-929c-11ea-9171-f302f1baf3a3.png)

ok，解决了，谢谢。

**Comment by kevinzhao2233** [comment]
@gitccl 你如果一直用这个自动加序号的主题，那就一直用早上给你这个主题就行，如果不需要自动加序号的话，就来再重新下载一下新的，我暂时解决不了兼容性的问题

**Comment by gitccl** [comment]
@kevinzhao2233 行
