### ISSUE TITLE
What should I do？

### ISSUE THREAD

**Issue by GodLei902** [kevinzhao2233/typora-theme-pie#5]
![image](https://user-images.githubusercontent.com/62991927/84112834-112b8780-aa5c-11ea-94fa-d362b59a690b.png)

**Comment by Hanyuze-iu** [comment]
![image](https://user-images.githubusercontent.com/62991927/84112856-1b4d8600-aa5c-11ea-809b-10f74e0b23b2.png)

**Comment by kevinzhao2233** [comment]
这可能并不是这款主题造成的，你可以卸载重新安装试试，如果试过了，那我也不清楚怎么回事
