### ISSUE TITLE
代码选中高亮可阅读性太差

### ISSUE THREAD

**Issue by xianzheTM** [kevinzhao2233/typora-theme-pie#6]
![image](https://user-images.githubusercontent.com/25103583/87848448-34770b80-c913-11ea-8d61-9d001d752d00.png)
选中后很难看清.

**Comment by kevinzhao2233** [comment]
稍微优化了下，谢谢你
下载最新的主题文件即可体验

![image](https://user-images.githubusercontent.com/42138464/87871386-7a4ed500-c9e2-11ea-90e8-848328e5611f.png)
