### ISSUE TITLE
导出pdf好像有点问题

### ISSUE THREAD

**Issue by adougebabi** [kevinzhao2233/typora-theme-pie#7]
![image](https://user-images.githubusercontent.com/19430567/92698499-0d6f1000-f37f-11ea-956c-c613f421b7e8.png)
从上到下是 一个#到5个#。
直接导出pdf和生成html再打印都是一样的问题

**Comment by kevinzhao2233** [comment]
我刚刚测试了下，确实有一个问题，导出 HTML 默认会在标题上添加链接，导致出现一个很短的下划线，但是你展示的情况并没有出现哎，你可以把你这段 markdown 的源码和生成的HTML源码分享一下吗（用记事本打开就是源码）。对了，你的电脑是Windows 还是 mac 呢
![image](https://user-images.githubusercontent.com/42138464/92740717-8d619e00-f3b0-11ea-93bc-221c32b0f3f7.png)

**Comment by adougebabi** [comment]
这个是pdf导出截图所以没有那个短横线，系统是Mac 10.15.6，导出html打开的确也会有这个短横线。源码的有点多不好贴，我打压缩包了。
[归档 2.zip](https://github.com/kevinzhao2233/typora-theme-pie/files/5202536/2.zip)

**Comment by kevinzhao2233** [comment]
好的，非常感谢，我是 Windows，明天我找个 mac 看看到底什么情况，尽快修复这个 bug，非常非常感谢

**Comment by est7** [comment]
> 好的，非常感谢，我是 Windows，明天我找个 mac 看看到底什么情况，尽快修复这个 bug，非常非常感谢

这个问题以前导出时没出现过，今天导出时也发现了

**Comment by est7** [comment]
是typora的问题，最新的更新版本已经把这个issue fix了 @kevinzhao2233 @adougebabi

**Comment by kevinzhao2233** [comment]
@est7 我的 0.9.95 还有这个问题，试试等等新版吧

**Comment by est7** [comment]
> @est7 我的 0.9.95 还有这个问题，试试等等新版吧

我目前Typora Beta 0.9.9.35.2 正常，是另外这个主题的分割线的margin我个人觉得有点太宽了，自己改掉了，其他都很棒，谢谢分享

**Comment by kevinzhao2233** [comment]
@est7 非常感谢

**Comment by adougebabi** [comment]
更新了后的确没问题了

**Comment by lavender010101** [comment]
导出某个文件为PDF失败了，是文件大小的问题吗，另一个文件可以成功导出
