### ISSUE TITLE
Missing fonts on export

### ISSUE THREAD

**Issue by henshin** [kevinzhao2233/typora-theme-pie#8]
When using the export functionality in Typora using the Pie theme, the fonts are not exported correctly.
I looked into other themes, and I believe you should use something like this at the top of your `.css` file:
```css
@include-when-export url(https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Source+Sans+Pro&display=swap);
```
This fixes the fonts when exporting but you should confirm if this is the recommended way to do it

**Comment by kevinzhao2233** [comment]
Thank you, this problem is fixed now, but in fact this method can only take effect when you can access google smoothly. It still cannot be used in other places, such as China, but it is still a good method.
