### ISSUE TITLE
点击无序列表项首部后出现抖动

### ISSUE THREAD

**Issue by wanguano** [kevinzhao2233/typora-theme-pie#9]
### 本主题演示效果图:
![](https://cdn.jsdelivr.net/gh/wanguano/cloudPic/img/20201107203216.gif)

### 其他主题演示效果图:
![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/20201107202648.gif)

**Comment by kevinzhao2233** [comment]
问题已经修复，你重新下载试试看。谢谢你的反馈，一行代码的问题你都写这么详细的 issue，真的感谢~~
